name: Metrics
on:
  workflow_dispatch:
  schedule:
    # "24:00 action" - This cron expression will run the workflow at midnight (00:00) every day.
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: generate github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.CZTANGT_TOKEN }}
          # Options
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai